QUESTION_BANK = {
    "Software Developer": [
        {"question": "What is object-oriented programming and why is it useful?", "reference": "Object-oriented programming organizes software into objects that combine data and behavior. Encapsulation, inheritance, polymorphism and abstraction improve code reuse and maintainability.", "keywords": ["object", "encapsulation", "inheritance", "polymorphism", "reuse"]},
        {"question": "What is the difference between a list and a tuple in Python?", "reference": "A list is mutable, so items can be changed. A tuple is immutable after creation. Lists suit changing collections, while tuples are useful for fixed data.", "keywords": ["list", "tuple", "mutable", "immutable", "change"]},
        {"question": "How would you debug a program that is giving the wrong output?", "reference": "I would reproduce the issue, compare actual and expected output, isolate the problem, use logging or a debugger, fix the cause, and test edge cases.", "keywords": ["reproduce", "expected", "debugger", "test", "error"]},
        {"question": "What is an API?", "reference": "An API is a defined way for software systems to communicate. A client sends a request to an endpoint and receives a response, commonly using HTTP and JSON.", "keywords": ["application", "interface", "request", "response", "HTTP"]},
        {"question": "Why is version control important in a software project?", "reference": "Version control tracks code changes, lets developers collaborate safely, supports branches and code review, and makes it possible to restore an earlier version.", "keywords": ["changes", "collaborate", "branch", "restore", "git"]},
        {"question": "Explain the difference between front-end and back-end development.", "reference": "Front-end development builds the user interface in the browser. Back-end development handles server logic, APIs, authentication and database operations. They communicate through HTTP requests.", "keywords": ["user interface", "browser", "server", "database", "API"]},
        {"question": "What are HTTP status codes? Give a few examples.", "reference": "HTTP status codes describe the result of a web request. For example 200 means success, 201 means created, 404 means not found, and 500 means server error.", "keywords": ["HTTP", "200", "404", "request", "server"]},
        {"question": "How do you make a web application secure?", "reference": "I would validate input, use authentication and authorization, hash passwords, use HTTPS, prevent SQL injection with parameterized queries, prevent cross-site scripting, and update dependencies.", "keywords": ["validate", "authentication", "password", "HTTPS", "SQL injection"]},
        {"question": "What is unit testing and why is it valuable?", "reference": "Unit testing checks a small isolated piece of code automatically. It catches regressions early, documents expected behavior, makes refactoring safer and improves confidence in quality.", "keywords": ["isolated", "automatic", "regression", "refactoring", "quality"]},
        {"question": "What is a database index and when would you use one?", "reference": "A database index speeds up searching and sorting rows. I would add indexes to frequently filtered or joined columns, while considering that indexes use storage and can slow writes.", "keywords": ["speed", "search", "columns", "query", "writes"]},
    ],
    "Data Analyst": [
        {"question": "What steps would you take to clean a dataset?", "reference": "I would inspect data, handle missing values, remove duplicates, correct data types and formats, identify outliers, validate the result and document decisions.", "keywords": ["missing", "duplicates", "types", "outliers", "validate"]},
        {"question": "What is the difference between correlation and causation?", "reference": "Correlation means two variables move together. Causation means one variable directly changes another. Correlation alone does not prove causation because other factors may be responsible.", "keywords": ["relationship", "cause", "variables", "prove", "factor"]},
        {"question": "How do you choose a chart for presenting data?", "reference": "I consider the question and data type. Bar charts compare categories, line charts show trends over time, scatter plots show relationships, and labels should be clear for the audience.", "keywords": ["bar", "line", "trend", "categories", "audience"]},
        {"question": "What is a KPI?", "reference": "A Key Performance Indicator is a measurable value that shows progress toward a business objective. A useful KPI is relevant to a goal, clearly defined, measurable and reviewed regularly.", "keywords": ["key performance indicator", "measure", "goal", "business", "progress"]},
        {"question": "How would you explain a complex analysis to a non-technical manager?", "reference": "I would start with the business question and main insight, use simple language and visuals, explain the impact and recommendation, and provide technical detail only if requested.", "keywords": ["business", "simple", "visual", "insight", "recommendation"]},
        {"question": "What is the difference between mean and median?", "reference": "The mean is the arithmetic average of values. The median is the middle value after sorting. Median is more robust when data contains extreme outliers.", "keywords": ["average", "middle", "sorted", "outliers", "values"]},
        {"question": "How would you investigate a sudden drop in sales?", "reference": "I would validate the data, segment sales by product, channel and region, compare prior periods, investigate changes such as pricing or stock, and report likely causes.", "keywords": ["validate", "segment", "product", "region", "compare"]},
        {"question": "What is data visualization and why does it matter?", "reference": "Data visualization uses charts and graphs so people can see patterns, trends, comparisons and outliers. It helps communicate useful insights for better decisions.", "keywords": ["charts", "patterns", "trends", "insights", "decisions"]},
        {"question": "What is an outlier and how would you handle it?", "reference": "An outlier is an unusually high or low observation. I would investigate whether it is a data error or real case, then document whether to correct, exclude or retain it based on the goal.", "keywords": ["unusual", "error", "investigate", "exclude", "document"]},
        {"question": "Why is SQL useful for a data analyst?", "reference": "SQL lets analysts retrieve, filter, join, aggregate and summarize data from relational databases. It prepares reliable datasets efficiently before analysis and reporting.", "keywords": ["retrieve", "filter", "join", "aggregate", "database"]},
    ],
    "HR Executive": [
        {"question": "How would you handle a conflict between two employees?", "reference": "I would listen to each employee privately and fairly, collect facts, encourage respectful communication, help them find a solution, document the outcome, and follow up.", "keywords": ["listen", "fair", "facts", "solution", "follow up"]},
        {"question": "What makes an effective recruitment process?", "reference": "An effective process starts with a clear job description, fair sourcing and screening, structured job-related interviews, timely communication, reference checks and a respectful candidate experience.", "keywords": ["job description", "fair", "interview", "criteria", "candidate"]},
        {"question": "How can employee engagement be improved?", "reference": "Engagement improves through clear goals, recognition, growth opportunities, supportive managers, regular feedback, fair policies and listening to employee concerns.", "keywords": ["recognition", "growth", "feedback", "manager", "goals"]},
        {"question": "Why is confidentiality important in HR?", "reference": "HR handles sensitive personal and company information. Confidentiality builds employee trust, protects privacy, supports fairness and helps meet legal and ethical responsibilities.", "keywords": ["sensitive", "privacy", "trust", "legal", "ethical"]},
        {"question": "How would you give constructive feedback to an employee?", "reference": "I would give feedback privately and promptly, describe specific behavior and impact, listen to the employee, agree improvement steps, offer support and set a follow-up date.", "keywords": ["specific", "behavior", "impact", "improvement", "follow-up"]},
        {"question": "How would you onboard a new employee effectively?", "reference": "I would prepare access and documents, introduce the team and culture, clarify role goals, provide training and a buddy, schedule check-ins and collect feedback during the first months.", "keywords": ["team", "goals", "training", "check-ins", "feedback"]},
        {"question": "How do you ensure fairness in interviews?", "reference": "I would use the same job-related criteria and structured questions for every candidate, avoid discriminatory questions, use a consistent rubric, involve trained interviewers and document decisions.", "keywords": ["criteria", "structured", "consistent", "discriminatory", "document"]},
        {"question": "What would you do if an employee reported harassment?", "reference": "I would listen carefully, ensure safety and confidentiality within policy limits, document the report, explain the process, investigate promptly and impartially, avoid retaliation, and take action.", "keywords": ["listen", "confidentiality", "document", "investigate", "retaliation"]},
        {"question": "How can HR use employee turnover data?", "reference": "HR can analyze turnover by team, tenure, role and reason for leaving to identify patterns. The findings can guide retention through onboarding, manager support, compensation or career development.", "keywords": ["turnover", "patterns", "retention", "onboarding", "development"]},
        {"question": "What is the purpose of a performance review?", "reference": "A performance review aligns goals, recognizes achievements, discusses performance evidence, identifies development needs, gives feedback and creates a plan for improvement and growth.", "keywords": ["goals", "achievements", "feedback", "development", "improvement"]},
    ],
}


def get_roles():
    return list(QUESTION_BANK.keys())


def get_questions(role: str):
    return QUESTION_BANK.get(role, [])
